### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by dfornika** [matsengrp/smctc#14]
I'm working on packaging a phylogenetics program that depends on SMCTC for the 'conda' package manager:

https://github.com/bioconda/bioconda-recipes/pull/5855

The program (`sts-online`) currently pulls in SMCTC as a git submodule, but I'm not able to use that  mechanism to pull the dependency into the conda 'recipe'. Could someone tag a release at commit `ad95bfc75293405003aaad4e0c67d6db6a558612`? I should then be able to package SMCTC as a conda recipe and use that as a dependency for `sts-online`

**Comment by dfornika** [comment]
@bcclaywell @4ment

**Comment by bcclaywell** [comment]
Tagged as `sts-0.1`.

**Comment by dfornika** [comment]
Thanks!

**Comment by dfornika** [comment]
Just a quick follow-up: this package was merged into bioconda yesterday:

https://anaconda.org/bioconda/sts-smctc
